disp('1. go to folder with file painting.png (example: cd ../images)')
disp('2. run Bmv_guihomography (function of Balu Toolbox)')
disp('3. press bottom Load')
disp(['4. type ' char(39) 'painting.png' char (39) ' (with apostrophes)'])
disp('5. play with the buttons of the GUI to rotate, translate and change the perspective oof the painting') 